### PR TITLE
Add retrieval of template id for Qualys WAS

### PR DESCRIPTION
**Pull request by qmontal**
These changes add a new functionality to qualysapi which allows to get the template id for the vulnerability data from Qualys WAS. It has been already in production in https://github.com/HASecuritySolutions/VulnWhisperer for a long time but it was maintained as a qualysapi fork until now.

### CODE REVIEW

**Comment by qmontal** [comment]
@paragbaxi I believe this error has to do with the configuration of pytest itself?

`pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (pytest 3.3.0 (/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages), Requirement.parse('pytest>=3.6'))!
make: *** [test] Error 1`

It breaks when checking with python 2.7 which would make sense if requirement is >=3.6, but it shouldn't fail on 3.6 then. The error is the same in both.

**Comment by paragbaxi** [comment]
agreed. have any advice on how to fix?

**Comment by qmontal** [comment]
I have no clue... 😥

**Comment by qmontal** [comment]
As the fail is not related to the PR code (the other tests are passing) but to the pytest config file used in the Travis CI instance, could the PR be checked for a merge? :)

**Comment by qmontal** [comment]
@paragbaxi whenever you are able, not in a hurry, could you update the release in PyPi? Thanks a lot for merging the PR :)

**Comment by paragbaxi** [comment]
SyntaxError: encoding problem: future_fstrings

**Comment by paragbaxi** [comment]
done

**Comment by qmontal** [comment]
Thanks a lot!

**Pull request merged**
