### PR TITLE
Python 3 support (2)

### PR DESCRIPTION
**Pull request by uovobw**
Replicated changes originally in https://github.com/paragbaxi/qualysapi/pull/21 by @tonybaloney by reapplying 2to3, modernize and pep8 on the tree.

- Update namespace imports to absolute
- Update setup.py for python 2/3 support flags

License not updated, please advise if changes are needed.

### CODE REVIEW

**Comment by uovobw** [comment]
@paragbaxi any updates on this PR?

**Comment by paragbaxi** [comment]
@uovobw would you like to be a maintainer on pypi? This way you can update the pip package.

**Comment by uovobw** [comment]
@paragbaxi i have never maintained a package on pip, but i'd really like to. i'll bother you a bit if i'm unsure about the process. thanks!

**Comment by paragbaxi** [comment]
@uovobw , great! Just let me know your pypi username so I can assign you as a maintainer.

**Comment by uovobw** [comment]
@paragbaxi with amazing creativity and unparalled fantasy my pypi username is `uovobw`

**Comment by tram0004** [comment]
I'd love it if you got this on pypi! Any way I can convince you two to do it? Thanks!

**Comment by paragbaxi** [comment]
uovobw is a maintainer but I can push it now.

**Comment by uovobw** [comment]
i have little knowledge of the pypi publishing process to be honest, but it should not be too complex.
i am a bit worried that by pushing it there the code will be picked up by anyone doing a pip install or similar and i am not 100% sure the current py3 version is working, i have had limited time to test it as the focus of the project i was using this code for has been shifted a bit. 
if you are ok with this we might push tagging it as "not production ready" (not sure how to do that, i'll check it once i'm done being on airplanes, sorry) for the py3 branch only and then groom it a bit once we have a bit more testing done. let me know, thanks

**Pull request merged**
