### PR TITLE
Update connector.py

### PR DESCRIPTION
**Pull request by lamusmaser**
Adds "verify" parameter, for pass-through to requests being made. This uses the same parameterization as the requests function.

### CODE REVIEW

**Comment by paragbaxi** [comment]
https://travis-ci.com/paragbaxi/qualysapi/jobs/272284670 failed
Can you please fixx @lamusmaser

**Comment by lamusmaser** [comment]
I'll see what I can do. I see that it is only failing on Style + Security (latter not overly applicable) w/ Python 3.8, so I will see if I can get an instance of 3.8 installed to check on that.
I also see that there is a session variable that holds verify, so I might look at handling that instead, if I can't get it to work through the tests this way.

**Comment by lamusmaser** [comment]
@paragbaxi, After running the tests locally, I got the following:
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> black --check qualysapi/ setup.py tests/
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\connector.py: unknown encoding: future_fstrings
Oh no! 💥 💔 💥
11 files would be left unchanged, 1 file would fail to reformat.

This looks to be an issue with the how it is seeing the encoding, which I did not modify. Is this a problem with the merged code?

**Comment by lamusmaser** [comment]
I pulled a fresh copy of the base release and attempted to perform the same tests. None of the qualysapi files succeeded for the same reason.

```
(qualysapitests) PS E:\scripting_misc\qualysapitests> git clone --depth=50 https://github.com/paragbaxi/qualysapi.git paragbaxi/qualysapi
Cloning into 'paragbaxi/qualysapi'...
remote: Enumerating objects: 755, done.
remote: Counting objects: 100% (755/755), done.
remote: Compressing objects: 100% (313/313), done.

Receiving objects: 100% (755/755), 150.93 KiB | 3.35 MiB/s, done.
Resolving deltas: 100% (487/487), done.
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> cd .\paragbaxi\qualysapi
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> black --check qualysapi/ setup.py tests/
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_actions.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\settings.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\connector.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\util.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\config.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_methods.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_objects.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\tests\context.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\tests\test_smoke.py: unknown encoding: future_fstrings
Oh no! 💥 💔 💥
3 files would be left unchanged, 9 files would fail to reformat.
```

This leads me to believe that there is an issue with how black is reading the .py files, specifically with the future_fstrings notation at the beginning of the files.

**Comment by paragbaxi** [comment]
This is the travis log
```
$ git clone --depth=50 https://github.com/paragbaxi/qualysapi.git paragbaxi/qualysapi
0.01s
Setting environment variables from .travis.yml
$ export TOX_TESTENV_PASSENV='TRAVIS TRAVIS_*'
$ export TOX_SKIP_MISSING_INTERPRETERS=False
$ export COVERALLS_SERVICE_NAME=travis-ci
$ export TOXENV=style
0.00s$ source ~/virtualenv/python3.8/bin/activate
cache.1
Setting up build cache
cache.pip
$ python --version
Python 3.8.0
$ pip --version
pip 19.3.1 from /home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pip (python 3.8)
install
1.01s$ pip3 install 'tox < 3.15'
8.92s$ tox
GLOB sdist-make: /home/travis/build/paragbaxi/qualysapi/setup.py
style create: /home/travis/build/paragbaxi/qualysapi/.tox/style
style installdeps: black == 19.10b0, isort[pyproject] == 4.3.21
style inst: /home/travis/build/paragbaxi/qualysapi/.tox/.tmp/package/1/qualysapi-6.0.1.zip
style installed: appdirs==1.4.3,attrs==19.3.0,black==19.10b0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,future-fstrings==1.2.0,idna==2.8,isort==4.3.21,lxml==4.4.2,pathspec==0.7.0,qualysapi==6.0.1,regex==2019.12.20,requests==2.22.0,toml==0.10.0,typed-ast==1.4.0,urllib3==1.25.7
style run-test-pre: PYTHONHASHSEED='168421658'
style run-test: commands[0] | isort --check-only --recursive qualysapi/ setup.py tests/
style run-test: commands[1] | black --check qualysapi/ setup.py tests/
would reformat /home/travis/build/paragbaxi/qualysapi/qualysapi/connector.py
Oh no! 💥 💔 💥
1 file would be reformatted, 11 files would be left unchanged.
ERROR: InvocationError for command /home/travis/build/paragbaxi/qualysapi/.tox/style/bin/black --check qualysapi/ setup.py tests/ (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   style: commands failed
The command "tox" exited with 1.
cache.2
store build cache
Done. Your build exited with 1.
```

**Comment by lamusmaser** [comment]
> @paragbaxi, After running the tests locally, I got the following:
> 
> ```
> (qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> black --check qualysapi/ setup.py tests/
> error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\connector.py: unknown encoding: future_fstrings
> Oh no! 💥 💔 💥
> 11 files would be left unchanged, 1 file would fail to reformat.
> ```
> 
> This looks to be an issue with the how it is seeing the encoding, which I did not modify. Is this a problem with the merged code?

@paragbaxi, after running a local test, this is what I see from that same run - this is an issue with how it is reading the encoding for future_fstrings. This is an issue with Black, not with the code that I modified. See also the response I gave earlier that shows that a Black test run on QualysAPI 6.0.1 without my modifications, where it fails for each of the qualysapi python files.

**Comment by lamusmaser** [comment]
@paragbaxi Additionally, looking at previous PR's tests, the failing check was only recently made a non-optional entity. This would be the reason why it previously passed build, but now is unable to succeed.

I would look into how we can pass build - this may take quite a few edits to get this working as expected, but it is definitely not tied to this specific PR.

Specifically, it looks like:
We are having issues with Black processing the style encoding of future-fstrings, which isn't really being used in the code.
We haven't been compliant with style for at least the past few PRs.
There was a modification made to the accepted tests, so that style is now a required check, but this wasn't run against the code to ensure compliance before making the modification.

I'm happy to help with making more PRs to get us in style-compliance, it will just be a lot more than just what this PR is specifically doing.

**Comment by lamusmaser** [comment]
It looks like @CMeza99 was the one to make the commit which enforced Style.

@CMeza99, were you able to get a good run of the code after the commit? I have been unable to get this to run successfully.

**Comment by CMeza99** [comment]
The test `style` is for coding style enforcement. The [black](https://github.com/psf/black) formatter is saying it wants to make changes (meaning the formating does not comply). Perhaps we need a `CONTRIBUTORS.md` at the root of the project to clarify styling.

**Comment by lamusmaser** [comment]
It looks like it is failing out before that point - see the test runs before that, specifically the test in this comment: https://github.com/paragbaxi/qualysapi/pull/73#issuecomment-570799731

I was unable to find any information on why specifically future_fstrings was not a correct encoding - can we confirm this before moving forward? I agree with you that styling should definitely be taken into account for future releases (and I would be happy to update the code base to comply), but the modifications made for this commit do not entail significant enough changes to the code base that this would suddenly throw this off; specifically, I was copying existing lines and modifying them to allow for the minor feature update.

**Comment by CMeza99** [comment]
Oh. I believe that, in your dev env, `black` is not running from the virtualenv `qualysapitests` (i.e. system python or another virtualenv (like with pipsi/pipx)) and it does not have the `future_fstring` library. This is why `tox` and the Travis CI log has a different output.

To eliminate this confusion, we could drop support for Python 3.5 and the need for `future_strings`. Python 3.5 is EOL Sept 13, 2020 (see https://devguide.python.org/#status-of-python-branches). (This would be my preferred solution. 😊

**Comment by lamusmaser** [comment]
> Oh. I believe that, in your dev env, `black` is not running from the virtualenv `qualysapitests` (i.e. system python or another virtualenv (like with pipsi/pipx)) and it does not have the `future_fstring` library. This is why `tox` and the Travis CI log has a different output.
> 
> To eliminate this confusion, we could drop support for Python 3.5 and the need for `future_strings`. Python 3.5 is EOL Sept 13, 2020 (see https://devguide.python.org/#status-of-python-branches). (This would be my preferred solution. 😊

I wanted to check if the dev env didn't get caught properly, so I quickly ran a test to see what's up - looks like things are working as intended. But, I definitely believe that there is a significant difference from the Travis CI implementation; I'm just not sure how to replicate it locally for local tests before uploading. In any case, I would probably agree with your approach, honestly. Seems like the easiest amount of work that has the largest impact (when I did that test, it actually gave me good results).

See below.
```
PS E:\scripting_misc\qualysapitests> .\Scripts\activate
(qualysapitests) PS E:\scripting_misc\qualysapitests> pip install future_fstrings
Requirement already satisfied: future_fstrings in e:\scripting_misc\qualysapitests\lib\site-packages (1.2.0)
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
(qualysapitests) PS E:\scripting_misc\qualysapitests> cd .\paragbaxi\qualysapi\
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> black --check qualysapi/ setup.py tests/
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_methods.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_actions.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\config.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\settings.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\util.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\connector.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\tests\context.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\api_objects.py: unknown encoding: future_fstrings
error: cannot format E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\tests\test_smoke.py: unknown encoding: future_fstrings
Oh no! 💥 💔 💥
3 files would be left unchanged, 9 files would fail to reformat.
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import future_fstrings
>>> quit()
```

**Comment by CMeza99** [comment]
`tox -e style` should yield the same results locally as in Travis CI.

(I should update `tox.ini` to better automatically run tests that would run in Travis. So, that all anyone has to do is `tox` to run them all.)

**Comment by lamusmaser** [comment]
Great, thank you for your help in getting this to run locally.

Here is the output of that, which ran as expected on the base code.

```
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> tox -e style
GLOB sdist-make: E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\setup.py
style create: E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\.tox\style
style installdeps: black == 19.10b0, isort[pyproject] == 4.3.21
style inst: E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\.tox\.tmp\package\1\qualysapi-6.0.1.zip
style installed: appdirs==1.4.3,attrs==19.3.0,black==19.10b0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,future-fstrings==1.2.0,idna==2.8,isort==4.3.21,lxml==4.4.2,pathspec==0.7.0,qualysapi==6.0.1,regex==2020.1.8,requests==2.22.0,toml==0.10.0,typed-ast==1.4.0,urllib3==1.25.7
style run-test-pre: PYTHONHASHSEED='582'
style run-test: commands[0] | isort --check-only --recursive qualysapi/ setup.py tests/
style run-test: commands[1] | black --check qualysapi/ setup.py tests/
All done! ✨ 🍰 ✨
12 files would be left unchanged.
_______________________________________________________ summary _______________________________________________________
  style: commands succeeded
  congratulations :)
```

And here it is after making my minor modifications:

```
(qualysapitests) PS E:\scripting_misc\qualysapitests\paragbaxi\qualysapi> tox -e style
GLOB sdist-make: E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\setup.py
style inst-nodeps: E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\.tox\.tmp\package\1\qualysapi-6.0.1.zip
style installed: appdirs==1.4.3,attrs==19.3.0,black==19.10b0,certifi==2019.11.28,chardet==3.0.4,Click==7.0,future-fstrings==1.2.0,idna==2.8,isort==4.3.21,lxml==4.4.2,pathspec==0.7.0,qualysapi==6.0.1,regex==2020.1.8,requests==2.22.0,toml==0.10.0,typed-ast==1.4.0,urllib3==1.25.7
style run-test-pre: PYTHONHASHSEED='177'
style run-test: commands[0] | isort --check-only --recursive qualysapi/ setup.py tests/
style run-test: commands[1] | black --check qualysapi/ setup.py tests/
would reformat E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\qualysapi\connector.py
Oh no! 💥 💔 💥
1 file would be reformatted, 11 files would be left unchanged.
ERROR: InvocationError for command 'E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\.tox\style\Scripts\black.EXE' --check qualysapi/ setup.py tests/ (exited with code 1)
_______________________________________________________ summary _______________________________________________________
ERROR:   style: commands failed
```

Alright, so now that I match Travis CI, I'll have to see what I can do to resolve the issue locally. I have a feeling there is something not passing through properly at some point, but I'll take on that troubleshooting component.

**Comment by CMeza99** [comment]
You could run `E:\scripting_misc\qualysapitests\paragbaxi\qualysapi\.tox\style\Scripts\black.EXE`. Since it would be running from an environment where all the dependencies were installed, it should produce the expected results.

**Comment by lamusmaser** [comment]
@CMeza99 This helped. I was able to get my local tests completed successfully. Newly pushed commit is testing now.

**Comment by lamusmaser** [comment]
Looks like other failures occurred. I'll work on those at this point, now that we have Black working, and I have a better understanding of the testing structure overall.

**Comment by paragbaxi** [comment]
#75 completed  as it's related

**Comment by CMeza99** [comment]
What is the use case to set `verify` to `False`?

**Comment by lamusmaser** [comment]
The default (```verify``` being set to ```True```) tells Requests to verify the SSL certificate for HTTPS requests.
In the cases where it cannot verify (typically for self-signed certificates or third-party signed certificates that aren't part of the default CAs from openssl), you will see this come through where you need to either set the path to a CA_BUNDLE or directory of trusted CAs OR you can set ```verify``` to ```False``` and this will not attempt to verify the SSL certificate.
Specifically, this use case came through for a Private Cloud Platform QualysGuard instance where it is using a self-signed certificate. After building the code locally for it, this looked specifically like a feature that would be nice for anyone else that might run into a similar problem; this could also be mitigated by passing through a **kwargs to the Request calls being made, but I felt that specifically requesting them would be better feature-wise and package-security-wise.

**Comment by lamusmaser** [comment]
@paragbaxi The build is passing now.

**Comment by paragbaxi** [comment]
fine with that

**Pull request merged**
