### PR TITLE
qualys section name as argument

### PR DESCRIPTION
**Pull request by qmontal**
This change is for being allowed to specify the section name that contains the qualys credentials, so that you can work with different qualys solutions using the same config file. If no section name is specified, default section name continues being "info".

Thanks for the library!

### CODE REVIEW

**Comment by qmontal** [comment]
This is currently needed for the [VulnWhisperer project](https://github.com/austin-taylor/VulnWhisperer), as we have different qualys modules integrated, and as the value is hardcoded, at the moment you can't use at the same time the different qualys modules unles they are sharing all of the config (hostname, user, password), which is kind of inconvenient :(

**Comment by qmontal** [comment]
@paragbaxi one question, every when the qualysapi version from pip repository is updated? I was thinking that maybe if it takes a long time, just use the fork with this PR while it gets through the whole process.

Thanks a lot!

**Comment by paragbaxi** [comment]
Want pip access?

**Comment by qmontal** [comment]
Yep, that would be great :D Thanks @paragbaxi!

**Comment by paragbaxi** [comment]
pypi username pls

**Pull request merged**
